<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!--
    1、如何修改promise的状态
    - resolve: pending => resolved
    - reject: pending => rejected
    - throw: pending => rejected

    2、Promise能否执行多个回调？
    - 可以执行多个回调

    3、改变promise状态和指定回调函数谁先谁后？
    - 都有可能，正常情况下是先指定回调函数，再改变状态（因为指定回调一般是同步的，更改状态一般是放在异步完成的回调里面的）
    - 如何先改变状态再指定回调函数？
      - 在执行器中直接调用resolve、reject
      - 延迟更长时间才调用then
    - 什么时候才能得到数据？
      - 如果先指定回调，那当状态发生改变时，回调函数就会被调用，得到数据
      - 如果先改变状态，那当指定回调时，回调函数就会被调用，得到数据
    
    4、then方法返回的结果由什么决定？
    - 简单描述：由then方法指定的回调函数执行的结果决定，这个返回的结果是一个新的promise对象
    - 详细表述：
      - 如果抛出异常，新promise变为rejected，错误信息为抛出的异常
      - 如果返回的是非promise的任意值，新promise变为resolved，值为返回的值
      - 如果返回的是一个promise，此promise的结果就会成为新promise的结果
      - 如果没有返回，新的promise变为resolved，值为undefined

    5、promise如何串联多个任务？
    - 使用.then()

    6、异常穿透：最后的一个catch会捕捉到前面的then当中的错误，会一层层往下传递

    7、中断promise链
    - 多次调用then方法，形成一个链，称为promise链
    - 有且只有一个方法，即返回一个pending状态下的promise
    - return new Promise(() => {});
    - 注意：这里的中断是指的是后续的then和catch都不会再执行，而throw只能使得then不再执行，catch还是会执行的

  -->
</body>
<script>
  // 2、Promise能否执行多个回调？
  // const p1 = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve("成功的结果");
  //   }, 500);
  // });
  // p1.then(res => {
  //   console.log(`1 ${res}`); // 1 成功的结果
  // })
  // p1.then(res => {
  //   console.log(`2 ${res}`); // 2 成功的结果
  // });
  
  // 3、如何先改变状态再指定回调函数？
  // 在执行器中直接调用resolve、reject
  // const p1 = new Promise((resolve, reject) => {
  //   resolve("成功的结果");
  // });
  // p1.then(res => {
  //   console.log(res);
  // });
  
  // 3、如何先改变状态再指定回调函数？
  // 延迟更长时间才调用then
  // const p1 = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve("成功的结果");
  //   }, 500);
  // });
  // setTimeout(() => {
  //   p1.then(res => {
  //     console.log(res);
  //   });
  // }, 1000);
  
  // 4、then方法返回的结果由什么决定？
  // const p1 = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve("成功的结果");
  //     reject("失败的结果");
  //   }, 500);
  // });
  // let p2 = p1.then((res) => {
  //   // throw "抛出异常";
  //   // return "返回一个非promise的值";
  //   // return new Promise((resolve) => { resolve("返回了一个新的promise"); });
  // }, (err) => {
  //   // throw "抛出异常";
  //   // return "返回一个非promise的值";
  //   // return new Promise((resolve) => { resolve("返回了一个新的promise"); });
  // });
  // p2.then(res => {
  //   console.log(`p2 res ${res}`);
  // }).catch(err => {
  //   console.log(`p2 err ${err}`);
  // });

  // 5、promise如何串联多个任务？
  // const p1 = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve("成功的结果1");
  //   }, 500);
  // });
  // p1.then(res => {
  //   console.log(res); // 成功的结果1
  //   return new Promise((resolve, reject) => {
  //     resolve("成功的结果2");
  //   });
  // }).then(res => {
  //   console.log(res); // 成功的结果2
  // }).then(res => {
  //   console.log(res); // undefined
  // });

  // 6、异常穿透
  // const p1 = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve("成功的结果1");
  //   }, 500);
  // });
  // p1.then(() => {
  //   console.log(111);
  //   throw "发生错误";
  // }).then(() => {
  //   console.log(222);
  // }).then(() => {
  //   console.log(333);
  // }).catch(err => {
  //   console.log("Error: " + err);
  // });

  // 7、中断promise链
  const p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("成功的结果1");
    }, 500);
  });
  p1.then(() => {
    console.log(111);
  }).then(() => {
    console.log(222);
    return new Promise(() => {});
  }).then(() => {
    console.log(333);
  }).catch(err => {
    console.log(err);
  });
</script>
</html>